{% set name = "pypyr" %}
{% set version = "5.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypyr-{{ version }}.tar.gz
  sha256: 22bb5686cffe5036cbdda810222cebf4967a4dd5828e915db130116e37ecca6c

build:
  number: 0
  noarch: python
  entry_points:
    - pypyr=pypyr.cli:main
  script: 
    - {{ PYTHON }} -m flit build
    - {{ PYTHON }} -m flit install
 
requirements:
  host:
    - pip
    - python >=3.7
    - flit
  run:
    - python >=3.7
    - python-dateutil
    - ruamel.yaml
    - tomli
    - tomli-w

test:
  imports:
    - pypyr
    - pypyr.cache
  commands:
    - pip check
    - pypyr --help
  requires:
    - pip

about:
  home: https://pypyr.io
  summary: task-runner for automation pipelines defined in yaml. cli & api.
  dev_url: https://github.com/pypyr/pypyr/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sclare87
